function [map]=str_tensor_map(matrix)
v=1;
EA=XFract_Diff(matrix,v);
GA=YFract_Diff(matrix,v);
FA=EA.*GA;
EEA=EA.*EA;
GGA=GA.*GA;
e1=0.5*((EEA+GGA)+sqrt((EEA-GGA).^2+4*FA.*FA)); 
e2=0.5*((EEA+GGA)-sqrt((EEA-GGA).^2+4*FA.*FA)); 
map=sqrt((e1+e2).^2+0.5*((e1-e2).^2));